### ISSUE TITLE
[CHECKLIST] Road to v1 of Webb docs

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-docs#2]
# Overview

The below list of tasks outline what is required to complete the Webb docs refactor.

[WIP] Webb Documentation content can be found in Notion here:
- [Webb Docs](https://www.notion.so/hicommonwealth/Webb-Docs-f840b22704614c69b08ee3f621f309cc)

### General
- [x] Remove fork
- [x] Delete old repo

### Content
- [x] Update  **Getting Started** section 
- [ ] Add project roadmap details
- [x] Update  **DKG** section
- [x] Review additional pages for the  **DKG** section
- [x] Update **Anchor Protocol** section
- [ ] Add technical roadmap for anchor protocol
- [x] Add guides for how to interact with bridge 
- [ ] Add deployments section that outlines the addresses of deployments
- [ ] Add governance section
- [x] Update **Relayer** overview section
- [ ] Update installation and usages sections of **Relayer**
- [ ] Add back **Advanced** section with relevant pages
- [ ] Add content around **arkworks gadget**
- [ ] Review and update diagrams
- [ ] Beautify diagrams for improved appeal 
- [ ] Add sdk documentation for installation and usage 

### Code
- [x] Remove all substrate related code/specifics from docs section
- [x] Remove substrate hub homepage and unnecessary dependencies 
- [ ] Set up deployment pipeline with staging and production sites using netlify
- [ ] Add CI checks 
- [x] Add proper domain name for prod

### Implementation Documentation 
- [x]  protocol-solidity docs ([typedocs](https://typedoc.org/))
- [x]  protocol-substrate rust docs
- [x]  dkg-substrate rust docs
- [x] arkworks api reference

### Final Checks 
- [ ] Content read through for accuracy, readability, grammar, and spelling
- [ ] Functionality checks for all buttons, and links
- [ ] Deployment pipeline works with staging and prod environments
