### ISSUE TITLE
[TASK] Document relayer setup, onboarding and usage 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-docs#21]
## Overview 

Currently the docs only provide relayer setup for hosted nodes, and does not outline how to become a relayer for the protocol / network. We need to provide clear instructions on how someone can become a relayer. 

### Tasks

- [x] Create a page for 'How to become a relayer' 
- [x] Provide a clear description of the different components a user can run to participate on the network (e.g. governance, tx relaying, data querying)
- [x] Outline clear steps on how to setup and configure the relayer
- [x] Define and establish a process for onboarding relayers for private tx relaying and dApp integration 
- [x] Provide diagrams of the relayer network, and how the relayers interact with the system as a whole

### Examples 

- [Tornado cash relayer docs](https://docs.tornado.cash/general/how-to-become-a-relayer)

**Comment by dutterbutter** [comment]
Blocked by https://github.com/webb-tools/relayer/issues/195

**Comment by dutterbutter** [comment]
Related to this work/discussion: https://github.com/webb-tools/relayer/issues/202
