### ISSUE TITLE
[TASK] Document how to become a node operator 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-docs#22]
## Overview

The current docs do not provide potential network participants with clear instruction on how to become a node operator for the Egg network. These docs should be straight forward to follow and include instructions on configuration, key management, resource requirements, and best practices. 

### Tasks

- [x] Create a page for 'How to become a node operator' 
- [x] Provide clear instructions on how to setup nodes for the Egg network 
- [x] Indicate how to generate keys, purpose of those keys, and best practices 
- [x] Provide direction on how to monitor, and debug the node using prometheus, grafana, alert manager, and loki
- [x] Outline resource requirements for running the node
- [ ] Publish eggnet binary for easy installation 
- [ ] Add screenshots once eggnet network is up and running as a collator 
- [ ] Need to specify bond requirements for EGG tokens

### Examples

- [Polkadot how to run a validator ](https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot)
- [Cosmos validator setup ](https://hub.cosmos.network/main/validators/validator-setup.html)
