### ISSUE TITLE
[TASK] Document crowdloan details, rewards, how to contribute, claim and faq pages

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-docs#23]
## Overview

The current docs do not provide detail on our future crowdloan campaign for the Egg network on Kusama. These docs should be straight forward to follow and include instructions on how to contribute, claiming rewards, and faq.
### Tasks

- [ ] Create a page for 'Crowdloan event' 
- [ ] Create a page for 'Crowdloan rewards'
- [ ] Create a page for 'How to contribute to crowdloan' 
- [ ] Create a page for 'How to claim rewards' 
- [ ] Create a page for 'FAQ' related to crowdloan campaign  

### Examples

- [Acala ](https://wiki.acala.network/acala-network/acala-crowdloan)
- [Moonbeam ](https://moonbeam.foundation/moonbeam-crowdloan/)
