### ISSUE TITLE
[TASK] Document user guides, and faq for vanchor, mixer  

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-docs#25]
## Overview

We will want to educate the user on how to utilize our dApp by providing clear documentation / instructions on how to use the various service offering (e.g. bridge, mixer). These user guides will be readily available to the user from the dApp interface. In addition, we should curate FAQ for each service in an effort to answer common user questions which will also be readily available to the user from the dApp interface. 

### Tasks 

- [ ] Document clear instruction set with screenshot on how to utilize the mixer
- [ ] Provide insights into the different operations of the mixer (e.g. what the secret note is for) 
- [ ] Curate potential frequently asked questions regarding the mixer
- [ ] Document clear instruction set with screenshot on how to utilize the bridge
- [ ] Provide insights into the different operations of the bridge (e.g. what the secret note is for) 
- [ ] Curate potential frequently asked questions regarding the bridge

**Comment by dutterbutter** [comment]
This will also cover the related links for education component for these flows.
