### ISSUE TITLE
[TASK] Tangle | Review and simplify setup/usage instructions

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-docs#72]
## Overview

We want to make it as easy as possible for external users to run a Tangle node(s). In an ideal state, users will download Tangle binary, setup applicable keys if running validator/collator node, start node with applicable flags. 

We should review and update the docs site to achieve the above flow.

### Task Checklist

- [x] Add script to docs site to download Tangle binary and ensure docker image is versioned and available 
- [x] Review and update [Required Keys](https://docs.webb.tools/docs/tangle-network/node-operators/required-keys/)
- [x] Review existing documentation for the following sections to ensure its accuracy:
     - [x] Deploying with Docker section 
     - [x] Deploying using Systemd
     - [x] Payouts
